[project]
name = "my-first-django-project"
version = "0.1.0"
<<<<<<< HEAD
description = "Add your description here"
=======
description = "Jaguar Kovalev"
>>>>>>> 525a4ba (Сделана первая версия МП для ДЗ)
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
]
